<?php
$descripciones_dinamicas = [
  'Distancia de Poder' => [
    'de -4.1 a -5' => 'Rechaza jerarquías. Cree que toda autoridad debe ganarse el respeto. Espera igualdad en trato, decisiones horizontales.',
    'de -3.1 a -4' => 'Cuestiona la autoridad si no la percibe como justa. Busca participación en decisiones y transparencia en liderazgos.',
    'de -2.1 a -3' => 'Prefiere relaciones horizontales. Aprecia la cercanía con figuras de autoridad pero acepta cierto liderazgo formal.',
    'de -1.1 a -2' => 'Cuestiona reglas estrictas. Prefiere liderazgos accesibles y decisiones participativas, aunque acepta jerarquías suaves.',
    'de -0.1 a -1' => 'Le resulta incómoda la autoridad rígida. Prefiere estructuras planas, pero coopera con jerarquías si son flexibles.',
    'de 0 a 1' => 'Se adapta a jerarquías siempre que sean claras y respetuosas. Valora el liderazgo bien ejercido.',
    'de 1.1 a 2' => 'Acepta la jerarquía como parte natural. Espera instrucciones claras y estructuras de autoridad definidas.',
    'de 2.1 a 3' => 'Cree que el respeto se basa en jerarquía. Evita confrontar a figuras de autoridad.',
    'de 3.1 a 4' => 'Ve la autoridad como necesaria y no cuestionable. Obedece sin dificultad a superiores.',
    'de 4.1 a 5' => 'Acepta el poder como natural y jerárquico. Confía ciegamente en la autoridad y en estructuras rígidas.',
  ],
  'Individualismo vs. Colectivismo' => [
    'de -4.1 a -5' => 'Altamente colectivista. Prioriza el grupo sobre lo individual. Lealtad fuerte, sentido de deber comunitario.',
    'de -3.1 a -4' => 'Fuerte enfoque grupal. Cree en el bienestar colectivo y toma decisiones basadas en lo que beneficia al equipo.',
    'de -2.1 a -3' => 'Valora el grupo, pero puede expresar su opinión individual. Equilibrio entre metas personales y colectivas.',
    'de -1.1 a -2' => 'Le importa su entorno, pero también sus metas personales. Busca el equilibrio entre el yo y los demás.',
    'de -0.1 a -1' => 'Oscila entre pensamiento individual y grupal. Sabe colaborar, pero también busca autonomía.',
    'de 0 a 1' => 'Es autónomo, pero sabe trabajar en grupo. Respeta la individualidad sin romper la cooperación.',
    'de 1.1 a 2' => 'Tiende a decidir por sí mismo. Valora su autonomía y evita depender de otros para definir su camino.',
    'de 2.1 a 3' => 'Alta autonomía. Se motiva por metas personales. Disfruta tomar decisiones sin intervención externa.',
    'de 3.1 a 4' => 'Muy independiente. Valora el logro individual por encima del consenso o el grupo.',
    'de 4.1 a 5' => 'Extremadamente individualista. Se enfoca solo en sus logros y responsabilidad personal.',
  ],
  'Resultados vs. Bienestar' => [
    'de -4.1 a -5' => 'Altamente orientado al bienestar. Valora la empatía, la cooperación y la armonía social por encima del éxito competitivo.',
    'de -3.1 a -4' => 'Muy orientado al bienestar. Da prioridad a la conciliación vida-trabajo y evita ambientes competitivos agresivos.',
    'de -2.1 a -3' => 'Orientación al cuidado y la inclusión. No busca destacar por encima de otros, promueve ambientes armoniosos.',
    'de -1.1 a -2' => 'Le importa el bienestar del grupo y su desarrollo personal, sin caer en competencia agresiva.',
    'de -0.1 a -1' => 'Busca balance entre logros y calidad de vida. Valora relaciones sin dejar de querer avanzar profesionalmente.',
    'de 0 a 1' => 'Combina ambición con humanidad. Puede competir, pero sin pisotear a otros. Busca armonía productiva.',
    'de 1.1 a 2' => 'Empieza a mostrar rasgos competitivos. Valora logros personales y reconocimiento por desempeño.',
    'de 2.1 a 3' => 'Orientado a logros visibles. Busca éxito individual, status y recompensa por méritos.',
    'de 3.1 a 4' => 'Alta orientación a resultados. Puede ser competitivo y priorizar metas sobre relaciones.',
    'de 4.1 a 5' => 'Extremadamente competitivo. Valora la fuerza, la ambición y el éxito material como fin último.',
  ],
  'Aversión a la Incertidumbre' => [
    'de -4.1 a -5' => 'Tolera y hasta disfruta la ambigüedad. Siente seguridad en entornos cambiantes. Rara vez busca certezas.',
    'de -3.1 a -4' => 'Alta tolerancia a la incertidumbre. Se adapta fácilmente y toma decisiones con poca información.',
    'de -2.1 a -3' => 'Confort con cierta ambigüedad. Le incomoda el control excesivo y valora la flexibilidad.',
    'de -1.1 a -2' => 'Sabe trabajar con incertidumbre, aunque agradece algo de estructura como punto de referencia.',
    'de -0.1 a -1' => 'Tolera la incertidumbre, pero prefiere tener alguna guía. Usa la intuición más que protocolos fijos.',
    'de 0 a 1' => 'Prefiere seguridad y orden sin rigidez. Se siente cómodo con normas si tienen lógica.',
    'de 1.1 a 2' => 'Busca certeza. Prefiere planes definidos, reglas claras y control de riesgos.',
    'de 2.1 a 3' => 'Estratega ante riesgos. Tiende a evitar ambigüedades. Confía más en procesos que en intuiciones.',
    'de 3.1 a 4' => 'Necesita control. Se siente incómodo en entornos inciertos. Prefiere protocolos estrictos.',
    'de 4.1 a 5' => 'Muy intolerante a la ambigüedad. Busca seguridad absoluta y evita cualquier desviación de normas.',
  ],
  'Orientación en el Plazo' => [
    'de -4.1 a -5' => 'Vive el presente. Enfocado en resultados inmediatos y soluciones prácticas. Poco interés en el largo plazo.',
    'de -3.1 a -4' => 'Favorece acciones de corto plazo. Enfocado en resultados inmediatos, con poca planificación a futuro.',
    'de -2.1 a -3' => 'Enfocado en beneficios rápidos. Tiene metas, pero no compromete demasiado el presente por el futuro.',
    'de -1.1 a -2' => 'Tiene metas a corto y mediano plazo. Mezcla planes prácticos con visión táctica.',
    'de -0.1 a -1' => 'Equilibra el presente y el futuro. Planifica, pero sin dejar de disfrutar el ahora.',
    'de 0 a 1' => 'Sabe planear y ejecutar en el presente. Tiene visión, pero disfruta los resultados parciales.',
    'de 1.1 a 2' => 'Planifica para el futuro. Tiene visión clara a mediano plazo y organiza recursos con anticipación.',
    'de 2.1 a 3' => 'Proyecta su vida a largo plazo. Aplaza recompensas inmediatas por objetivos más ambiciosos.',
    'de 3.1 a 4' => 'Alta orientación a futuro. Define metas de largo plazo y trabaja disciplinadamente para lograrlas.',
    'de 4.1 a 5' => 'Sacrifica el presente por el futuro. Fuerte autodisciplina y enfoque en planificación de largo plazo.',
  ],
  'Espontaneidad vs. Estructura' => [
    'de -4.1 a -5' => 'Extremadamente espontáneo. Busca placer, gratificación inmediata y libertad personal, incluso desafiando normas sociales.',
    'de -3.1 a -4' => 'Tiende a seguir impulsos. Busca libertad, placer y satisfacción sin preocuparse por estructuras rígidas.',
    'de -2.1 a -3' => 'Disfruta de la libertad, pero con algo de autocontrol. A veces sigue estructuras si no son demasiado restrictivas.',
    'de -1.1 a -2' => 'Aprecia el disfrute y la libertad, aunque reconoce la necesidad de reglas en ciertos contextos.',
    'de -0.1 a -1' => 'Le gusta disfrutar, pero entiende la necesidad de normas. Se mueve bien en contextos flexibles.',
    'de 0 a 1' => 'Disfruta la vida con responsabilidad. Valora la libertad, pero no rompe las normas esenciales.',
    'de 1.1 a 2' => 'Necesita cierta estructura. Tiende a evitar excesos y sigue normas aunque no le agraden todas.',
    'de 2.1 a 3' => 'Prefiere entornos regulados. Asocia disciplina con éxito. Evita impulsividad innecesaria.',
    'de 3.1 a 4' => 'Busca orden. Prefiere reglas estrictas. Siente incomodidad con libertad excesiva o ambigüedad.',
    'de 4.1 a 5' => 'Extremadamente estructurado. Siente necesidad constante de orden, control y normas estrictas.',
  ],
];
?>